name: SED Assignment CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

permissions: 
  contents: read 

jobs:
  tests-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup-python-action

      - name: Run unit tests
        run: pytest

  linting: 
    runs-on: ubuntu-latest
    permissions: write-all 
    steps: 
      - name: Checkout
        uses: actions/checkout@v4 

      - name: Setup Python and Install Dependencies
        uses: ./.github/actions/setup-python-action

      - name: Install Ruff
        run: pip install ruff

      - name: Lint with Ruff
        run: ruff check 

  codeql-analysis:
    if: ${{ !github.event.act }} # skip during local actions testing
    runs-on: ubuntu-latest
    permissions: write-all 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Initialise CodeQL
        uses: github/codeql-action/init@v3 
        with: 
          languages: 'javascript,python'

      - name: CodeQL autobuild
        uses: github/codeql-action/autobuild@v3

      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v3